"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $directory\
# $git_branch\
# $fill\
# $cmd_duration\
# $nodejs\
# $dotnet\
# $python\
# $java\
# $c\
# $golang\
# $os\
# $time\
# $hostname\
# $username\
# $line_break\
# $character\
# """
# minimal
format = """
$directory\
$git_branch\
$fill\
$cmd_duration\
$nodejs\
$dotnet\
$python\
$java\
$c\
$golang\
$time\
$line_break\
$character\
"""

add_newline = false 

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
purple = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"


[os]
format = '[ ](fg:blue)[$symbol ](fg:mantle bg:blue)[](fg:blue)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
format = '[](fg:peach)[󰷏 ](fg:mantle bg:peach)[](fg:peach bg:surface0)[ $read_only$truncation_symbol$path](fg:peach bg:surface0)[](fg:surface0)'
home_symbol = " ~"
truncation_symbol = ' '
truncation_length = 3 
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[ ](fg:sapphire)[$symbol](fg:surface0 bg:sapphire)[](fg:sapphire bg:surface0)[ $branch](fg:sapphire bg:surface0)[](fg:surface0)'
symbol = ' '

[nodejs]
format = '[ ](fg:green)[$symbol](fg:crust bg:green)[](fg:green bg:surface0)[ $version](fg:green bg:surface0)[](fg:surface0)'
symbol = '󰎙 '

[deno]
format = '[ ](fg:peach)[$symbol](fg:crust bg:peach)[](fg:peach bg:surface0)[ $version](fg:peach bg:surface0)[](fg:surface0)'

[golang]
format = '[ ](fg:sky)[$symbol](fg:crust bg:sky)[](fg:sky bg:surface0)[ $version](fg:sky bg:surface0)[](fg:surface0)'
symbol = '󰟓 '

[dotnet]
format = '([ ](fg:purple)[$symbol](fg:primary bg:purple)[](fg:purple bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[python]
format = '[ ](fg:purple)[$symbol](fg:crust bg:purple)[](fg:purple bg:surface0)[ $version](fg:purple bg:surface0)[](fg:surface0)'
symbol = ' '

[java]
format = '[ ](fg:red)[$symbol](fg:crust bg:red)[](fg:red bg:surface0)[ $version](fg:red bg:surface0)[](fg:surface0)'
symbol = ' '

[c]
format = '[ ](fg:blue)[$symbol](fg:crust bg:blue)[](fg:blue bg:surface0)[ $version](fg:blue bg:surface0)[](fg:surface0)'
symbol = ' '

[fill]
symbol = ' '
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[](fg:blue)[ ](fg:crust bg:blue)[](fg:blue bg:surface0)[ $duration ](fg:blue bg:surface0)[](fg:surface0)'

[time]
format = '[ ](fg:flamingo)[󰦖 ](fg:crust bg:flamingo)[](fg:flamingo bg:surface0)[ $time](fg:flamingo bg:surface0)[](fg:surface0)'
time_format = '%H:%M:%S'
disabled = false

[username]
format = '[ ](fg:yellow)[ ](fg:surface0 bg:yellow)[](fg:yellow bg:surface0)[ $user](fg:yellow bg:surface0)[](fg:surface0) '
show_always = true

[character]
success_symbol = "[❯](fg:bold green)"
error_symbol = "[❯](fg:bold red)"
