theme = "lackluster"

[editor]
line-number = "relative"
scrolloff = 8
auto-format = true
auto-completion = true
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.search]
smart-case = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 15

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.insert]
C-space = "completion"
