theme = "tokyonight_t"

[editor]
line-number = "relative"
cursorline = true
scrolloff = 8
auto-format = true
auto-completion = true
auto-info = true
end-of-line-diagnostics = "hint"
popup-border = "all"

[editor.search]
smart-case = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.insert]
C-space = "completion"

[editor.inline-diagnostics]
cursor-line = "warning"
