# Editor theme
theme = "catppuccin_mocha"

# Editor settings
[editor]
line-number = "relative"
scrolloff = 8
auto-format = true
auto-completion = true
auto-info = true

[editor.lsp]
enable = true
display-messages = true

[editor.soft-wrap]
enable = true
max-wrap = 15

[editor.statusline]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.search]
smart-case = true

[editor.whitespace.render]
nbsp = "all"
tab = "all"
newline= "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.insert]
C-c = "normal_mode"
C-space = "completion"
