[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
node = "latest"
ripgrep = "latest"
usage = "latest"
fzf = "latest"
fd = "latest"
bat = "latest"
rust = "latest"
go = "latest"
gh = "latest"
neovim = "latest"
starship = "latest"
zoxide = "latest"
zig = "latest"
lazygit = "latest"
helix = "latest"
uv = "latest"
zellij = "latest"
opencode = "latest"
pnpm = "latest"
